<#
Prints (or applies) the Windows hosts-file entries for every gateway vhost,
sourced directly from infra/compose.support.yaml's gateway network `aliases:`
list -- the single source of truth for what the gateway actually routes, so
this can't drift out of sync with a hand-copied list.

Usage:
    pwsh tools/hosts/print-entries.ps1              # print only
    pwsh tools/hosts/print-entries.ps1 -Apply        # append missing entries
                                                      # to the hosts file (run
                                                      # as Administrator)
#>
param(
    [switch]$Apply
)

$ErrorActionPreference = "Stop"

$repoRoot = (& git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) { $repoRoot = (Resolve-Path "$PSScriptRoot/../..").Path }

$composePath = Join-Path $repoRoot "infra/compose.support.yaml"
$content = Get-Content $composePath -Raw

# Pull every "- <name>.eaop-logistics.localhost" line out of the aliases:
# block -- a plain regex over the file, not a full YAML parse, since the
# aliases are simple flat strings with no nesting to worry about.
$hostnames = [regex]::Matches($content, '-\s+([\w.-]+\.eaop-logistics\.localhost)') |
    ForEach-Object { $_.Groups[1].Value } |
    Sort-Object -Unique

if (-not $hostnames) {
    Write-Error "No *.eaop-logistics.localhost aliases found in $composePath"
    exit 1
}

$beginMarker = "# BEGIN eaop-logistics (generated by tools/hosts/print-entries.ps1 -- do not edit inside this block by hand)"
$endMarker = "# END eaop-logistics"

$lines = $hostnames | ForEach-Object { "127.0.0.1 $_" }

if (-not $Apply) {
    Write-Host $beginMarker
    $lines | ForEach-Object { Write-Host $_ }
    Write-Host $endMarker
    exit 0
}

$hostsFile = "$env:SystemRoot\System32\drivers\etc\hosts"
$existing = Get-Content $hostsFile -ErrorAction SilentlyContinue

if ($existing -contains $beginMarker) {
    # Block already present -- only append entries genuinely missing from
    # the file (inside or outside the block), don't nest a second
    # begin/end pair around them.
    $toAdd = $lines | Where-Object { $existing -notcontains $_ }
    if (-not $toAdd) {
        Write-Host "All entries already present in $hostsFile"
        exit 0
    }
    Write-Host "Adding $($toAdd.Count) entr$(if ($toAdd.Count -eq 1) {'y'} else {'ies'}) to $hostsFile (existing eaop-logistics block found)..."
    Add-Content -Path $hostsFile -Value $toAdd -Encoding ASCII
    $toAdd | ForEach-Object { Write-Host "  + $_" }
    exit 0
}

$toAdd = $lines | Where-Object { $existing -notcontains $_ }
if (-not $toAdd) {
    Write-Host "All entries already present in $hostsFile"
    exit 0
}

Write-Host "Adding $($toAdd.Count) entr$(if ($toAdd.Count -eq 1) {'y'} else {'ies'}) to $hostsFile (new eaop-logistics block)..."
Add-Content -Path $hostsFile -Value $beginMarker -Encoding ASCII
Add-Content -Path $hostsFile -Value $toAdd -Encoding ASCII
Add-Content -Path $hostsFile -Value $endMarker -Encoding ASCII
$toAdd | ForEach-Object { Write-Host "  + $_" }
