"""Write identity/projections/entra.yaml from infra/entra/'s already-applied
Terraform state -- the reverse direction of write_keycloak_tfvars.py (that
one generates INPUT for provisioning; this one reads OUTPUT from an
already-provisioned tenant). Client IDs only, never secrets -- secrets stay
in Vault (identity/credentials-inventory.yaml's existing posture).

Usage: uv run --with pyyaml python -m tools.identity.write_entra_projection
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
ENTRA_TERRAFORM_DIR = ROOT / "infra" / "entra"
OUT_PATH = ROOT / "identity" / "projections" / "entra.yaml"

# client_id (Keycloak-style key, e.g. "tms-mcp-svc") -> canonical_id --
# same mapping identity/projections/keycloak.yaml's `clients:` section
# already declares, reused here since it's the same set of machine
# identities, just a different provider's client ids for them.
_CANONICAL_ID_BY_CLIENT_KEY = {
    "lane-evaluation-agent-svc": "agent.lane-evaluation",
    "commercial-normalization-agent-svc": "agent.commercial-normalization",
    "route-decision-agent-svc": "agent.route-decision",
    "tms-mcp-svc": "workload.tms-mcp",
    "rate-mcp-svc": "workload.rate-mcp",
    "qms-mcp-svc": "workload.qms-mcp",
    "approval-mcp-svc": "workload.approval-mcp",
    "mission-control-api-svc": "workload.mission-control",
}


def _terraform_output(name: str) -> dict:
    result = subprocess.run(
        ["terraform", "output", "-json", name],
        cwd=ENTRA_TERRAFORM_DIR, capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    client_ids = _terraform_output("machine_identity_client_ids")
    tenant_id = _terraform_output("authenticated_tenant")

    clients = {}
    unmapped = []
    for client_key, client_id in client_ids.items():
        canonical_id = _CANONICAL_ID_BY_CLIENT_KEY.get(client_key)
        if canonical_id is None:
            unmapped.append(client_key)
            continue
        clients[canonical_id] = {"client_id": client_id}

    # entra.yaml has TWO halves (see its own header comment): the
    # pre-apply input half (tenant_domain/app_registrations, consumed by
    # gen_entra.py to build Terraform input) and this script's post-apply
    # write-back half (tenant_id/clients, read from already-applied
    # state). This script owns ONLY the second half -- it must preserve
    # whatever pre-apply keys already exist in the file rather than
    # overwriting the whole document, or every run silently destroys the
    # other half (a real regression this comment exists to prevent).
    existing: dict = {}
    if OUT_PATH.exists():
        existing = yaml.safe_load(OUT_PATH.read_text(encoding="utf-8")) or {}
    preserved = {k: v for k, v in existing.items() if k not in ("tenant_id", "clients")}

    doc = {**preserved, "tenant_id": tenant_id, "clients": clients}
    OUT_PATH.write_text(
        "# Entra-specific projection. Two halves, both real:\n"
        "#   - tenant_domain/app_registrations: PRE-apply input, consumed by\n"
        "#     tools/identity/gen_entra.py (M3.3) to build Terraform input --\n"
        "#     mirrors identity/projections/keycloak.yaml's naming-only shape.\n"
        "#   - tenant_id/clients: POST-apply write-back, generated by THIS\n"
        "#     script from infra/entra/'s already-applied Terraform state\n"
        "#     (machine_identity_client_ids output). Client IDs only, never\n"
        "#     secrets -- secrets stay in Vault. Mirrors keycloak.yaml's shape\n"
        "#     so rfq_common.pep.resolve._client_id_maps() can merge both.\n"
        "#   This script only ever rewrites tenant_id/clients -- the other\n"
        "#   half is preserved from whatever was already in the file.\n\n"
        + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_PATH}: {len(clients)} clients" + (f" (unmapped: {unmapped})" if unmapped else ""))


if __name__ == "__main__":
    main()
