"""Write identity/projections/entra.yaml from infra/entra/'s already-applied
Terraform state -- the reverse direction of write_keycloak_tfvars.py (that
one generates INPUT for provisioning; this one reads OUTPUT from an
already-provisioned tenant). Client IDs only, never secrets -- secrets stay
in Vault (identity/credentials-inventory.yaml's existing posture).

Usage: uv run --with pyyaml python -m tools.identity.write_entra_projection
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
ENTRA_TERRAFORM_DIR = ROOT / "infra" / "entra"
OUT_PATH = ROOT / "identity" / "projections" / "entra.yaml"

# client_id (Keycloak-style key, e.g. "tms-mcp-svc") -> canonical_id --
# same mapping identity/projections/keycloak.yaml's `clients:` section
# already declares, reused here since it's the same set of machine
# identities, just a different provider's client ids for them.
_CANONICAL_ID_BY_CLIENT_KEY = {
    "lane-evaluation-agent-svc": "agent.lane-evaluation",
    "commercial-normalization-agent-svc": "agent.commercial-normalization",
    "route-decision-agent-svc": "agent.route-decision",
    "tms-mcp-svc": "workload.tms-mcp",
    "rate-mcp-svc": "workload.rate-mcp",
    "qms-mcp-svc": "workload.qms-mcp",
    "approval-mcp-svc": "workload.approval-mcp",
}


def _terraform_output(name: str) -> dict:
    result = subprocess.run(
        ["terraform", "output", "-json", name],
        cwd=ENTRA_TERRAFORM_DIR, capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    client_ids = _terraform_output("machine_identity_client_ids")
    tenant_id = _terraform_output("authenticated_tenant")

    clients = {}
    unmapped = []
    for client_key, client_id in client_ids.items():
        canonical_id = _CANONICAL_ID_BY_CLIENT_KEY.get(client_key)
        if canonical_id is None:
            unmapped.append(client_key)
            continue
        clients[canonical_id] = {"client_id": client_id}

    doc = {
        "tenant_id": tenant_id,
        "clients": clients,
    }
    OUT_PATH.write_text(
        "# Entra-specific projection -- generated by tools/identity/write_entra_projection.py\n"
        "# from infra/entra/'s already-applied Terraform state (machine_identity_client_ids output).\n"
        "# Client IDs only, never secrets -- secrets stay in Vault. Mirrors identity/projections/\n"
        "# keycloak.yaml's shape so rfq_common.pep.resolve._client_id_maps() can merge both.\n\n"
        + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_PATH}: {len(clients)} clients" + (f" (unmapped: {unmapped})" if unmapped else ""))


if __name__ == "__main__":
    main()
